In [5]:
from gurobipy import *

milp_model = Model("milp")

In [6]:
# GIVING PARAMETER VALUES
import numpy as np
from numpy import random
    
b = random.randint(1,10, (4,1))
    
d = random.randint(1,10, (4,1))

while (np.sum(b)) < (np.sum(d)):
    b = random.randint(1,10, (4,1))
    d = random.randint(1,10, (4,1))
    if (np.sum(b)) >= (np.sum(d)):
            break
I=[]
J=[]
for m in range(4):
    if b[m][0]>d[m][0]:
        I.append(m)
    elif b[m][0]<d[m][0]:
        J.append(m)

C = random.randint(1,5,(4,4))
        
# DECISION VARIABLE

obj_fn = 0
for i in I:
    for j in J:
        xij = milp_model.addVar(vtype=GRB.CONTINUOUS, lb=0, )
        obj_fn += (C[i][j]*xij)
        
milp_model.setObjective(obj_fn, GRB.MINIMIZE)
    
# CONSTRAINTS  
for i in I:
    A=0
    for j in J:
        A += xij
    ci = milp_model.addConstr(A <= b[i][0]-d[i][0] )
for j in J:
    B=0
    for i in I:
        B += xij
    cj = milp_model.addConstr(B >= d[j][0]-b[j][0] )
            

milp_model.optimize()

Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 4 rows, 3 columns and 4 nonzeros
Model fingerprint: 0x276bf734
Coefficient statistics:
  Matrix range     [1e+00, 3e+00]
  Objective range  [2e+00, 3e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [3e+00, 6e+00]
Presolve removed 4 rows and 3 columns
Presolve time: 0.02s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    2.6666667e+00   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.05 seconds (0.00 work units)
Optimal objective  2.666666667e+00


In [7]:
for v in milp_model.getVars():
    print(v.varName, v.x)

C0 0.0
C1 0.0
C2 1.3333333333333333


In [8]:
I

[0, 1, 2]

In [9]:
J

[3]

In [93]:
b

array([[9],
       [8],
       [8],
       [5],
       [7],
       [3],
       [4],
       [9],
       [9],
       [7]])

In [94]:
d

array([[1],
       [9],
       [5],
       [3],
       [5],
       [4],
       [4],
       [9],
       [7],
       [3]])

In [87]:
C

array([[4, 1, 4, 4],
       [3, 2, 2, 2],
       [2, 3, 1, 3],
       [4, 1, 2, 2]])

In [ ]:
x = milp_model.addVar(C.shape[0], C.shape[1], vtype=GRB.CONTINUOUS, name="x")

In [24]:
for i in I:
    for j in J:
        xij = milp_model.addVar(vtype=GRB.CONTINUOUS, lb=0, name="xij")

obj_fn = sum(C[i,j]*xij for i in I for j in J)   
milp_model.setObjective(obj_fn, GRB.MINIMIZE)

A=0
B=0    
for i in I:
    for j in J:
        A += xij
    ci = milp_model.addConstr(A <= b[i][0]-d[i][0], "ci" )
for j in J:
    for i in I:
        B += xij
    ci = milp_model.addConstr(B >= b[j][0]-d[j][0], "cj" )



milp_model.optimize()

Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 4 rows, 3 columns and 4 nonzeros
Model fingerprint: 0xce3dfe95
Coefficient statistics:
  Matrix range     [1e+00, 3e+00]
  Objective range  [1e+01, 1e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e+01, 8e+01]
Presolve removed 4 rows and 3 columns
Presolve time: 0.01s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    0.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.02 seconds (0.00 work units)
Optimal objective  0.000000000e+00


In [25]:
for v in milp_model.getVars():
    print(v.varName, v.x)

xij 0.0
xij 0.0
xij 0.0


In [ ]:
A=0
B=0    
for i in I:
    for j in J:
        A += xij
    ci = milp_model.addConstr(A <= b[i][0]-d[i][0], "ci" )
for j in J:
    for i in I:
        B += xij
    ci = milp_model.addConstr(B <= b[j][0]-d[j][0], "cj" )

In [17]:
c1 = milp_model.addConstr(((sum(xij) for j in J) <= (b[i][0]-d[i][0]) 
                          for i in I),
                          "c1")

c2 = milp_model.addConstr(((sum(xij) for i in I) >= (d[j][0]-b[j][0]) 
                          for j in J),
                          "c2")

TypeError: unsupported operand type(s) for -: 'generator' and 'NoneType'

In [14]:
x02.x

NameError: name 'x02' is not defined

In [70]:
for i in I:
    for j in J:
        print(i,j)

1 3
2 3
